apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-doomed-depl
  annotations:
    description: "Deployment doomed to fail"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-2
  template:
    metadata:
      labels:
        app: nginx-2
    spec:
      containers:
      - name: nginx
        image: nginx:1:27.4-alpine
        ports:
        - containerPort: 80
        resources:
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-doomed-service
spec:
  selector:
    app: nginx-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
