apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          # When the average CPU usage across all nginx Pods exceeds 60%, new replicas will be added (maxReplicas; up to 6).
          # If CPU utilization drops below 60%, Kubernetes removes extra Pods, but not below the minimum replicas (minReplicas) 3.        
          averageUtilization: 60 